# Generated by Django 3.1.2 on 2020-10-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpots',
            fields=[
                ('spot_id', models.UUIDField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cost_per_hour', models.IntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('availability', models.IntegerField(choices=[(1, 'Section A'), (2, 'Section B'), (3, 'Section Ab')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_spot_reservation.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.UUIDField()),
                ('section', models.IntegerField(choices=[(1, 'Section A'), (2, 'Section B'), (3, 'Section Ab')])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Reserved'), (2, 'Parked'), (3, 'Completed'), (4, 'Cancelled')])),
                ('bill_amount', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking_spot_reservation.parkingspots')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_spot_reservation.user')),
            ],
        ),
    ]
