# Generated by Django 3.1.2 on 2020-10-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='vehicle_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspots',
            name='availability',
            field=models.IntegerField(choices=[(0, 'Reserved'), (1, 'Section A'), (2, 'Section B'), (3, 'Section Ab')]),
        ),
    ]
