# Generated by Django 3.1.2 on 2020-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot_reservation', '0002_auto_20201023_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='vehicle_number',
            field=models.CharField(max_length=10),
        ),
    ]
