# Generated by Django 3.1.2 on 2020-10-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot_reservation', '0003_auto_20201023_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='user_id',
            new_name='user',
        ),
    ]
